name: polyline_animation_plus
description: "A Flutter package for creating smooth, customizable polyline animations on Google Maps, ideal for transport, delivery, and route-visualization applications."
version: 1.0.4
homepage: https://github.com/MICHAELVM01/polyline_animation_plus
repository: https://github.com/MICHAELVM01/polyline_animation_plus
issue_tracker: https://github.com/MICHAELVM01/polyline_animation_plus/issues
documentation: https://github.com/MICHAELVM01/polyline_animation_plus
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter_platform_interface: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

topics:
  - map-animation
  - animated-polylines
